Create env-test.js
// webpack.config.js
const PORT_ENV = require('./env.js');
// Error: Cannot find module './env.js'

console.log('PORT_ENV =', PORT_ENV);